### ISSUE TITLE
Provide strict variant of Data.Map.Ordered

### ISSUE THREAD

**Issue by RyanGlScott** [dmwit/ordered-containers#10]
`Data.Map.Ordered` uses a lazy `Map` internally, so it is currently awkward to achieve an ordered map that is strict in its keys. I propose adding a new module (either named `Data.Map.Strict.Ordered` or `Data.Map.Ordered.Strict`, depending on your tastes) that provides the same API as `Data.Map.Ordered` but uses strict `Map` operations where necessary.

From a quick glance, it appears that the following operations would need to be implemented differently to be strict:

* `(<|)`
* `(|<)`
* `(>|)`
* `(|>)`
* `unionWithL`
* `unionWithR`
* `singleton`
* `fromList`
* `intersectionWith`

**Comment by dmwit** [comment]
Yep, seems reasonable to me.
