### ISSUE TITLE
Document insert/update operators

### ISSUE THREAD

**Issue by yaitskov** [dmwit/ordered-containers#24]
Differences between insert/update operators are not explained.

```
import Data.Map.Ordered as O

Prelude O> O.assocs $ O.empty >| (3,3) >| (2, 2) |> (1, 1)  >| (2,0)
[(3,3),(1,1),(2,0)]
Prelude O> O.assocs $ O.empty >| (3,3) >| (2, 2) |> (1, 1)  |> (2,0)
[(3,3),(2,0),(1,1)]
```

`(|>)` keeps insert index meanwhile `(>|)` gives new insert index

**Comment by dmwit** [comment]
The documentation contains the following sentence, which I believe captures the behavior you're describing:

> The pipe appears on the side whose indices take precedence if both sides contain the same key
