### ISSUE TITLE
Could/should OSet have instances for Semigroup and/or Monoid?

### ISSUE THREAD

**Issue by rcook** [dmwit/ordered-containers#3]
For example:

```haskell
instance Ord a => Semigroup (OSet a) where
    (<>) = foldl' (|>)

instance Ord a => Monoid (OSet a) where
    mempty = OSet.empty
```

I believe that these instances are lawful

If this is something that you think would be useful and appropriate, let me know and I'll submit a patch.

**Comment by rcook** [comment]
Actually, I guess the problem is which append operator, `|<>` vs. `<>|`, to choose. So, it's probably better not to choose one over the other.

**Comment by rcook** [comment]
See the comment on my pull request (https://github.com/dmwit/ordered-containers/pull/5). I think it would be more principled to have separate `OSetL` and `OSetR` wrappers exposing the two alternative `Semigroup` and `Monoid` instances.

I agree that the "left bias" of `fromList` strongly suggests that the "default" implementation for `Semigroup` would use `|<>` (which is exactly why I implemented it this way in my pull request). I'm not completely opposed to reopening my pull request, though I'm going to continue to experiment with my own `OSetL` and `OSetR` wrappers to see where that takes me!

**Comment by dmwit** [comment]
Your suggestion to have two newtype wrappers sounds good to me. Done.
